### PR TITLE
Update to before_action in userstamp.rb

### PR DESCRIPTION
**Pull request by matheussilvasantos**
before_filter is deprecated and will be removed in Rails 5.1

### CODE REVIEW

**Comment by delynn** [comment]
@matheussilvasantos Thanks for putting this together. Do you think it would be possible to support the `before_action` and `before_filter` method? This would ensure that people who haven't updated to Rails >5 would still be able to use the latest version of the code.

**Comment by matheussilvasantos** [comment]
Sorry, I don't know :(

**Comment by delynn** [comment]
No worries. I was thinking something like the following:

```
if base.respond_to?(:before_action)
  base.before_action :set_stamper
  base.after_action  :reset_stamper
else
  base.before_filter :set_stamper
  base.after_filter  :reset_stamper
end
```

**Comment by matheussilvasantos** [comment]
It's a good solution

**Pull request closed without merging**
